// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PujcovnaAut;

#nullable disable

namespace PujcovnaAut.Migrations
{
    [DbContext(typeof(PujcovnaContext))]
    [Migration("20251218174044_PridaniKoeficientu")]
    partial class PridaniKoeficientu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PujcovnaAut.Model.Auto", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SPZ")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<string>("Znacka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AutoId");

                    b.HasIndex("KategorieId");

                    b.ToTable("Auta");

                    b.HasData(
                        new
                        {
                            AutoId = 1,
                            KategorieId = 1,
                            Model = "Fabia III",
                            SPZ = "1P1 1234",
                            Stav = 0,
                            Znacka = "Škoda"
                        },
                        new
                        {
                            AutoId = 2,
                            KategorieId = 2,
                            Model = "Octavia IV",
                            SPZ = "2B5 5678",
                            Stav = 0,
                            Znacka = "Škoda"
                        },
                        new
                        {
                            AutoId = 3,
                            KategorieId = 1,
                            Model = "i30",
                            SPZ = "3A2 9012",
                            Stav = 0,
                            Znacka = "Hyundai"
                        },
                        new
                        {
                            AutoId = 4,
                            KategorieId = 2,
                            Model = "Golf VIII",
                            SPZ = "4C8 3456",
                            Stav = 0,
                            Znacka = "VW"
                        },
                        new
                        {
                            AutoId = 5,
                            KategorieId = 1,
                            Model = "Ceed",
                            SPZ = "5E7 7890",
                            Stav = 0,
                            Znacka = "Kia"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Kategorie", b =>
                {
                    b.Property<int>("KategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorieId"));

                    b.Property<decimal>("DenniSazba")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("KoeficientPoj")
                        .HasColumnType("float");

                    b.Property<string>("NazevKategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KategorieId");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            KategorieId = 1,
                            DenniSazba = 800m,
                            KoeficientPoj = 1.0,
                            NazevKategorie = "Economy"
                        },
                        new
                        {
                            KategorieId = 2,
                            DenniSazba = 1200m,
                            KoeficientPoj = 1.5,
                            NazevKategorie = "Standard"
                        },
                        new
                        {
                            KategorieId = 3,
                            DenniSazba = 2000m,
                            KoeficientPoj = 2.0,
                            NazevKategorie = "Premium"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Pojisteni", b =>
                {
                    b.Property<int>("PojisteniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PojisteniId"));

                    b.Property<decimal>("CenaZaDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NazevPlanu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PojisteniId");

                    b.ToTable("Pojisteni");

                    b.HasData(
                        new
                        {
                            PojisteniId = 1,
                            CenaZaDen = 150m,
                            NazevPlanu = "Basic"
                        },
                        new
                        {
                            PojisteniId = 2,
                            CenaZaDen = 250m,
                            NazevPlanu = "Standard"
                        },
                        new
                        {
                            PojisteniId = 3,
                            CenaZaDen = 400m,
                            NazevPlanu = "Full"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Vypujcka", b =>
                {
                    b.Property<int>("VypujckaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VypujckaId"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("CenaCelkem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("PocetDni")
                        .HasColumnType("int");

                    b.Property<int>("PojisteniId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<int>("ZakaznikId")
                        .HasColumnType("int");

                    b.HasKey("VypujckaId");

                    b.HasIndex("AutoId");

                    b.HasIndex("PojisteniId");

                    b.HasIndex("ZakaznikId");

                    b.ToTable("Vypujcky");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Zakaznik", b =>
                {
                    b.Property<int>("ZakaznikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZakaznikId"));

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZakaznikId");

                    b.ToTable("Zakaznici");

                    b.HasData(
                        new
                        {
                            ZakaznikId = 1,
                            DatumNarozeni = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jan.novak@email.cz",
                            Jmeno = "Jan",
                            Prijmeni = "Novák",
                            Telefon = "777123456"
                        },
                        new
                        {
                            ZakaznikId = 2,
                            DatumNarozeni = new DateTime(1985, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.dvorakova@seznam.cz",
                            Jmeno = "Eva",
                            Prijmeni = "Dvořáková",
                            Telefon = "608987654"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Auto", b =>
                {
                    b.HasOne("PujcovnaAut.Model.Kategorie", "Kategorie")
                        .WithMany("Auta")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Vypujcka", b =>
                {
                    b.HasOne("PujcovnaAut.Model.Auto", "Auto")
                        .WithMany("Vypujcky")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PujcovnaAut.Model.Pojisteni", "Pojisteni")
                        .WithMany("Vypujcky")
                        .HasForeignKey("PojisteniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PujcovnaAut.Model.Zakaznik", "Zakaznik")
                        .WithMany("Vypujcky")
                        .HasForeignKey("ZakaznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Pojisteni");

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Auto", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Kategorie", b =>
                {
                    b.Navigation("Auta");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Pojisteni", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Zakaznik", b =>
                {
                    b.Navigation("Vypujcky");
                });
#pragma warning restore 612, 618
        }
    }
}
