// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PujcovnaAut;

#nullable disable

namespace PujcovnaAut.Migrations
{
    [DbContext(typeof(PujcovnaContext))]
    [Migration("20251218165253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PujcovnaAut.Model.Auto", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SPZ")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<string>("Znacka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AutoId");

                    b.HasIndex("KategorieId");

                    b.ToTable("Auta");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Kategorie", b =>
                {
                    b.Property<int>("KategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorieId"));

                    b.Property<decimal>("DenniSazba")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NazevKategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("KategorieId");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            KategorieId = 1,
                            DenniSazba = 800m,
                            NazevKategorie = "Economy"
                        },
                        new
                        {
                            KategorieId = 2,
                            DenniSazba = 1200m,
                            NazevKategorie = "Standard"
                        },
                        new
                        {
                            KategorieId = 3,
                            DenniSazba = 2000m,
                            NazevKategorie = "Premium"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Pojisteni", b =>
                {
                    b.Property<int>("PojisteniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PojisteniId"));

                    b.Property<decimal>("CenaZaDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NazevPlanu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PojisteniId");

                    b.ToTable("Pojisteni");

                    b.HasData(
                        new
                        {
                            PojisteniId = 1,
                            CenaZaDen = 150m,
                            NazevPlanu = "Basic"
                        },
                        new
                        {
                            PojisteniId = 2,
                            CenaZaDen = 250m,
                            NazevPlanu = "Standard"
                        },
                        new
                        {
                            PojisteniId = 3,
                            CenaZaDen = 400m,
                            NazevPlanu = "Full"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Vypujcka", b =>
                {
                    b.Property<int>("VypujckaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VypujckaId"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("CenaCelkem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PojisteniId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<int>("ZakaznikId")
                        .HasColumnType("int");

                    b.HasKey("VypujckaId");

                    b.HasIndex("AutoId");

                    b.HasIndex("PojisteniId");

                    b.HasIndex("ZakaznikId");

                    b.ToTable("Vypujcky");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Zakaznik", b =>
                {
                    b.Property<int>("ZakaznikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZakaznikId"));

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZakaznikId");

                    b.ToTable("Zakaznici");

                    b.HasData(
                        new
                        {
                            ZakaznikId = 1,
                            DatumNarozeni = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jan.novak@email.cz",
                            Jmeno = "Jan",
                            Prijmeni = "Novák",
                            Telefon = "777123456"
                        },
                        new
                        {
                            ZakaznikId = 2,
                            DatumNarozeni = new DateTime(1985, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.dvorakova@seznam.cz",
                            Jmeno = "Eva",
                            Prijmeni = "Dvořáková",
                            Telefon = "608987654"
                        },
                        new
                        {
                            ZakaznikId = 3,
                            DatumNarozeni = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petr.svoboda@gmail.com",
                            Jmeno = "Petr",
                            Prijmeni = "Svoboda",
                            Telefon = "720111222"
                        },
                        new
                        {
                            ZakaznikId = 4,
                            DatumNarozeni = new DateTime(1988, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jana.novotna@post.cz",
                            Jmeno = "Jana",
                            Prijmeni = "Novotná",
                            Telefon = "602333444"
                        },
                        new
                        {
                            ZakaznikId = 5,
                            DatumNarozeni = new DateTime(1979, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "martin.cerny@email.cz",
                            Jmeno = "Martin",
                            Prijmeni = "Černý",
                            Telefon = "775555666"
                        },
                        new
                        {
                            ZakaznikId = 6,
                            DatumNarozeni = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucie.prochazkova@seznam.cz",
                            Jmeno = "Lucie",
                            Prijmeni = "Procházková",
                            Telefon = "731777888"
                        },
                        new
                        {
                            ZakaznikId = 7,
                            DatumNarozeni = new DateTime(1992, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tomas.kucera@centrum.cz",
                            Jmeno = "Tomáš",
                            Prijmeni = "Kučera",
                            Telefon = "603999000"
                        },
                        new
                        {
                            ZakaznikId = 8,
                            DatumNarozeni = new DateTime(1998, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "katka.vesela@gmail.com",
                            Jmeno = "Kateřina",
                            Prijmeni = "Veselá",
                            Telefon = "722123789"
                        },
                        new
                        {
                            ZakaznikId = 9,
                            DatumNarozeni = new DateTime(1983, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jakub.horak@email.cz",
                            Jmeno = "Jakub",
                            Prijmeni = "Horák",
                            Telefon = "776456123"
                        },
                        new
                        {
                            ZakaznikId = 10,
                            DatumNarozeni = new DateTime(1991, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "misa.nemcova@post.cz",
                            Jmeno = "Michaela",
                            Prijmeni = "Němcová",
                            Telefon = "605789123"
                        });
                });

            modelBuilder.Entity("PujcovnaAut.Model.Auto", b =>
                {
                    b.HasOne("PujcovnaAut.Model.Kategorie", "Kategorie")
                        .WithMany("Auta")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Vypujcka", b =>
                {
                    b.HasOne("PujcovnaAut.Model.Auto", "Auto")
                        .WithMany("Vypujcky")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PujcovnaAut.Model.Pojisteni", "Pojisteni")
                        .WithMany("Vypujcky")
                        .HasForeignKey("PojisteniId");

                    b.HasOne("PujcovnaAut.Model.Zakaznik", "Zakaznik")
                        .WithMany("Vypujcky")
                        .HasForeignKey("ZakaznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Pojisteni");

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Auto", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Kategorie", b =>
                {
                    b.Navigation("Auta");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Pojisteni", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("PujcovnaAut.Model.Zakaznik", b =>
                {
                    b.Navigation("Vypujcky");
                });
#pragma warning restore 612, 618
        }
    }
}
