// <auto-generated />
using System;
using DataEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntity.Migrations
{
    [DbContext(typeof(PujcovnaContext))]
    [Migration("20251230135149_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEntity.Auto", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<decimal>("CenaZaDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Obrazek")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RokVyroby")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SPZ")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<string>("Znacka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AutoId");

                    b.HasIndex("KategorieId");

                    b.ToTable("Auta");
                });

            modelBuilder.Entity("DataEntity.Kategorie", b =>
                {
                    b.Property<int>("KategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorieId"));

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DenniSazba")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("KoeficientPoj")
                        .HasColumnType("float");

                    b.Property<string>("NazevKategorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("KategorieId");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("DataEntity.Pojisteni", b =>
                {
                    b.Property<int>("PojisteniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PojisteniId"));

                    b.Property<decimal>("CenaZaDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazevPlanu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PojisteniId");

                    b.ToTable("Pojisteni");
                });

            modelBuilder.Entity("DataEntity.Vypujcka", b =>
                {
                    b.Property<int>("VypujckaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VypujckaId"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("CelkovaCena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CenaCelkem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<int>("PocetDni")
                        .HasColumnType("int");

                    b.Property<int>("PojisteniId")
                        .HasColumnType("int");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stav")
                        .HasColumnType("int");

                    b.Property<int>("ZakaznikId")
                        .HasColumnType("int");

                    b.HasKey("VypujckaId");

                    b.HasIndex("AutoId");

                    b.HasIndex("PojisteniId");

                    b.HasIndex("ZakaznikId");

                    b.ToTable("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Zakaznik", b =>
                {
                    b.Property<int>("ZakaznikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZakaznikId"));

                    b.Property<string>("CisloRP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZakaznikId");

                    b.ToTable("Zakaznici");
                });

            modelBuilder.Entity("DataEntity.Auto", b =>
                {
                    b.HasOne("DataEntity.Kategorie", "Kategorie")
                        .WithMany("Auta")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("DataEntity.Vypujcka", b =>
                {
                    b.HasOne("DataEntity.Auto", "Auto")
                        .WithMany("Vypujcky")
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataEntity.Pojisteni", "Pojisteni")
                        .WithMany("Vypujcky")
                        .HasForeignKey("PojisteniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataEntity.Zakaznik", "Zakaznik")
                        .WithMany("Vypujcky")
                        .HasForeignKey("ZakaznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Pojisteni");

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("DataEntity.Auto", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Kategorie", b =>
                {
                    b.Navigation("Auta");
                });

            modelBuilder.Entity("DataEntity.Pojisteni", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Zakaznik", b =>
                {
                    b.Navigation("Vypujcky");
                });
#pragma warning restore 612, 618
        }
    }
}
